//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nabrodov_WPF2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nabrodov_wpf2Entities1 : DbContext
    {
        public nabrodov_wpf2Entities1()
            : base("name=nabrodov_wpf2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

        private static nabrodov_wpf2Entities1 _context;

        public static nabrodov_wpf2Entities1 GetContext()
        {
            if (_context == null)
                _context = new nabrodov_wpf2Entities1();

            return _context;
        }
    }
}
