//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp_Nabrodov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotels_Image
    {
        public int Id { get; set; }
        public int HotelId { get; set; }
        public byte[] ImagePreview { get; set; }
    
        public virtual Hotels Hotels { get; set; }
    }
}
