//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp_Nabrodov
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourBaseEntities : DbContext
    {
        public TourBaseEntities()
            : base("name=TourBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Hotels_Comments> Hotels_Comments { get; set; }
        public virtual DbSet<Hotels_Image> Hotels_Image { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tours> Tours { get; set; }
        public virtual DbSet<TourType> TourType { get; set; }

        private static TourBaseEntities _context;
        public static TourBaseEntities GetContext()
        {
            if (_context  == null)
                _context = new TourBaseEntities();

            return _context;
        }
    }
}
