//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bilet5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }

        public string FormatStatus
        {
            get
            {
                return (Status == true) ? "Выполнено" : "Не выполнено";
            }
        }

        public string FormatTitle 
        { 
            get
            {
                char[] title = Title.ToCharArray();
                string stringTitle = "";

                if (title.Length > 20) 
                {
                    for (int i = 0; i < 20; i++)
                        stringTitle += title[i];

                    return stringTitle;
                }

                for (int i = 0; i < title.Length; i++)
                    stringTitle += title[i];


                return stringTitle;
            }
        }

        public string FormatDesc
        {
            get
            {
                char[] desc = Description.ToCharArray();
                string stringDesc = "";

                if (desc.Length > 50) 
                {
                    for (int i = 0; i < 50; i++)
                        stringDesc += desc[i];

                    return stringDesc;
                }
                for (int i = 0; i < desc.Length; i++)
                    stringDesc += desc[i];

                return stringDesc;
            }
        }
    }
}
