//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nabrodov_UserApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public bool admin { get; set; }

        public string adminText
        {
            get
            {
                return (admin == true) ? "Администратор" : "Пользователь";
            }
        }
    }
}
